n = int(input('Digite um numero para ver sua tabuada: '))
print('-' * 32)
print(f'{n} multiplicado por  1 é  = {n*1}')
print(f'{n} multiplicado por  2 é  = {n*2}')
print(f'{n} multiplicado por  3 é  = {n*3}')
print(f'{n} multiplicado por  4 é  = {n*4}')
print(f'{n} multiplicado por  5 é  = {n*5}')
print(f'{n} multiplicado por  6 é  = {n*6}')
print(f'{n} multiplicado por  7 é  = {n*7}')
print(f'{n} multiplicado por  8 é  = {n*8}')
print(f'{n} multiplicado por  9 é  = {n*9}')
print(f'{n} multiplicado por 10 é  = {n*10}')
print('-' * 32)